client_industry_mapping = {
    "Food & Beverages": "Food & Beverage",
    "Healthcare & Life Sciences": "Healthcare & Life Science",
    "Information, Tech & Telecommunications": "Information, Tech & Telecommunication",
    "Consumer Services": "Consumer Service",
    "NGOs": "NGO",
    "Advertising & Communications": "Advertising & Communication",
    "Logistics & Transportation": "Logistic & Transportation",
}


fb_page_category_mapping = {
    "Retirement and assisted living facility": "Health & Beauty",
    "Health/Beauty": "Health & Beauty",
    "Kitchen/Cooking": "Food & Beverage",
    "Product/Service": "Product/Service",
    "Performance & event venue": "Event & Entertainment",
    "Community": "Community & Non-profit",
    "Hospital": "Health & Beauty",
    "Laser hair removal service": "Health & Beauty",
    "Medical & health": "Health & Beauty",
    "Consulting agency": "Consulting",
    "Internet company": "Technology & Internet",
    "Financial consultant": "Finance & Consulting",
    "Charity organisation": "Community & Non-profit",
    "Jewellery/Watches": "Fashion & Accessories",
    "Engineering service": "Engineering & Construction",
    "App Page": "Technology & Internet",
    "Home improvement": "Home & Garden",
    "Property": "Real Estate",
    "Local business": "Local Services",
    "Financial service": "Finance & Consulting",
    "Clothing (brand)": "Fashion & Accessories",
    "Property developer": "Real Estate",
    "Cleaning service": "Home & Garden",
    "Information technology company": "Technology & Internet",
    "Malaysian restaurant": "Food & Beverage",
    "Vehicle parts shop": "Automotive",
    "General Practitioner": "Health & Beauty",
    "University": "Education",
    "Industrial company": "Industrial",
    "Non-governmental organisation (NGO)": "Community & Non-profit",
    "Block of flats": "Real Estate",
    "Private school": "Education",
    "Vending machine sales and service": "Retail",
    None: "Other",
    "Laundromat": "Home & Garden",
    "Education": "Education",
    "Pregnancy care centre": "Health & Beauty",
    "Coffee shop": "Food & Beverage",
    "Arts & crafts shop": "Retail",
    "Café": "Food & Beverage",
    "Business centre": "Office & Business",
    "Vehicle body shop": "Automotive",
    "Property service": "Real Estate",
    "Shoe shop": "Fashion & Accessories",
    "Family therapist": "Health & Beauty",
    "LASIK/Laser eye surgeon": "Health & Beauty",
    "Business service": "Office & Business",
    "Software company": "Technology & Internet",
    "Occupational health and safety service": "Health & Beauty",
    "Product/service": "Product/Service",
    "Beauty, cosmetic & personal care": "Health & Beauty",
    "Brokerage": "Finance & Consulting",
    "Financial planner": "Finance & Consulting",
    "Currency exchange": "Finance & Consulting",
    "Food wholesaler": "Food & Beverage",
    "Insurance company": "Insurance",
    "Community organisation": "Community & Non-profit",
    "Home decor": "Home & Garden",
    "Burger restaurant": "Food & Beverage",
    "Car dealership": "Automotive",
    "Ice cream shop": "Food & Beverage",
    "Steakhouse": "Food & Beverage",
    "Alternative & holistic health service": "Health & Beauty",
    "Tax preparation service": "Finance & Consulting",
    "Political party": "Politics & Government",
    "Retail company": "Retail",
    "Politician": "Politics & Government",
    "Political organisation": "Politics & Government",
    "Health & wellness website": "Health & Beauty",
    "Estate agent": "Real Estate",
    "Country club/Clubhouse": "Sports & Recreation",
    "Software": "Technology & Internet",
    "News & media website": "Media & Publication",
    "Heating, ventilating & air conditioning service": "Home & Garden",
    "Cars": "Automotive",
    "Public figure": "Other",
    "Optometrist": "Health & Beauty",
    "Furniture": "Home & Garden",
    "Educational consultant": "Education",
    "Appliance repair service": "Home & Garden",
    "E-commerce website": "Technology & Internet",
    "Vehicle shop": "Automotive",
    "Shopping & retail": "Retail",
    "Food & drink company": "Food & Beverage",
    "Bakery": "Food & Beverage",
    "Sportswear shop": "Fashion & Accessories",
    "Psychologist": "Health & Beauty",
    "Travel agent": "Travel & Tourism",
    "Property company": "Real Estate",
    "Intellectual property solicitor": "Legal Services",
    "Brand": "Fashion & Accessories",
    "Accountant": "Finance & Consulting",
    "Concrete contractor": "Construction & Contractors",
    "Skincare service": "Health & Beauty",
    "Commercial & industrial": "Industrial",
    "Water park": "Sports & Recreation",
    "Transport service": "Transportation",
    "General dentist": "Health & Beauty",
    "Pizza place": "Food & Beverage",
    "Vehicle dealership": "Automotive",
    "Management service": "Office & Business",
    "Supermarket/Convenience store": "Retail",
    "Fruit & vegetable shop": "Food & Beverage",
    "Book shop": "Retail",
    "Women's health clinic": "Health & Beauty",
    "Women's clothes shop": "Fashion & Accessories",
    "Vehicle service": "Automotive",
    "Energy company": "Utilities",
    "Massage therapist": "Health & Beauty",
    "Amusement & theme park": "Sports & Recreation",
    "Government building": "Politics & Government",
    "Tour Agency": "Travel & Tourism",
    "Performing arts": "Arts & Entertainment",
    "Tools/Equipment": "Home & Garden",
    "Pet supplies": "Pets & Animals",
    "Cabinet & worktop store": "Home & Garden",
    "Entrepreneur": "Other",
    "Agriculture": "Other",
    "Advertising agency": "Advertising & Marketing",
    "Marketing agency": "Advertising & Marketing",
    "Interior design studio": "Home & Garden",
    "Advertising/marketing": "Advertising & Marketing",
    "Medical lab": "Health & Beauty",
    "Meat wholesaler": "Food & Beverage",
    "Baby goods/Children's goods": "Children's Goods",
    "Educational Consultant": "Education",
    "Window installation service": "Home & Garden",
    "Dentist & dental surgery": "Health & Beauty",
    "Tutor/Teacher": "Education",
    "Mobile phone shop": "Electronics",
    "Home goods shop": "Home & Garden",
    "Education and learning": "Education",
    "Health food shop": "Food & Beverage",
    "Vitamins/Supplements": "Health & Beauty",
    "Business & economy website": "Technology & Internet",
    "Hair salon": "Health & Beauty",
    "Construction company": "Construction & Contractors",
    "Real Estate": "Real Estate",
    "Primary school": "Education",
    "Insurance Agent": "Insurance",
    "Local service": "Local Services",
    "Household supplies": "Home & Garden",
    "Business supplies service": "Office & Business",
    "Bar": "Food & Beverage",
    "Hotel & B&B": "Hospitality",
    "Contractor": "Construction & Contractors",
    "Patio/Garden": "Home & Garden",
    "Real Estate Developer": "Real Estate",
    "Concert tour": "Arts & Entertainment",
    "Wedding planning service": "Events & Entertainment",
    "Medical supply shop": "Health & Beauty",
    "Insurance agent": "Insurance",
    "Airline company": "Travel & Tourism",
    "Baby & children's clothing shop": "Children's Goods",
    "Vehicle repair shop": "Automotive",
    "Audiologist": "Health & Beauty",
    "Aquarium": "Pets & Animals",
    "Food service distributor": "Food & Beverage",
    "Appliances": "Home & Garden",
    "Biotechnology company": "Science & Technology",
    "Cosmetic dentist": "Health & Beauty",
    "Religious organisation": "Religion & Spirituality",
    "Specialist food shop": "Food & Beverage",
    "Orthopaedist": "Health & Beauty",
    "Public relations agency": "Advertising & Marketing",
    "Cargo & freight company": "Transportation",
    "Gym/Physical fitness centre": "Sports & Recreation",
    "Ophthalmologist": "Health & Beauty",
    "Electronics shop": "Electronics",
    "Day spa": "Health & Beauty",
    "Interest": "Other",
    "Education website": "Education",
    "Uniform supplier": "Fashion & Accessories",
    "Carpet & flooring shop": "Home & Garden",
    "Telecommunication company": "Technology & Internet",
    "Building Materials": "Home & Garden",
    "Vietnamese restaurant": "Food & Beverage",
    "Food & drink": "Food & Beverage",
    "Electrician": "Home & Garden",
    "Investment management company": "Finance & Consulting",
    "Concert Tour": "Arts & Entertainment",
    "Furniture store": "Home & Garden",
    "Cosmetics shop": "Health & Beauty",
    "Bookstore": "Retail",
    "Motivational speaker": "Other",
    "Investing service": "Finance & Consulting",
    "Electronics": "Electronics",
    "Information Technology Company": "Technology & Internet",
    "Doctor": "Health & Beauty",
    "Residence": "Real Estate",
    "Home removal company": "Transportation",
    "Smoothie & juice bar": "Food & Beverage",
    "Blinds & curtains shop": "Home & Garden",
    "Food delivery service": "Food & Beverage",
    "Butcher's shop": "Food & Beverage",
    "Motorsport shop": "Automotive",
    "Boutique": "Fashion & Accessories",
    "Beauty salon": "Health & Beauty",
    "Community group": "Community & Non-profit",
    "Home": "Home & Garden",
    "Motorbike dealership": "Automotive",
    "Entertainment website": "Arts & Entertainment",
    "Magazine": "Media & Publication",
    "Pet Service": "Pets & Animals",
    "Physical Therapist": "Health & Beauty",
    "Health/beauty": "Health & Beauty",
    "Phone/Tablet": "Electronics",
    "Hair replacement service": "Health & Beauty",
    "Fruit & Vegetable Store": "Food & Beverage",
    "Skin Care Service": "Health & Beauty",
    "Dermatologist": "Health & Beauty",
    "Hotel resort": "Hospitality",
    "Acupuncturist": "Health & Beauty",
    "Non-profit organisation": "Community & Non-profit",
    "Business Consultant": "Consulting",
    "Pest control service": "Home & Garden",
    "School": "Education",
    "Cleaning Service": "Home & Garden",
    "Construction Company": "Construction & Contractors",
    "Telemarketing service": "Office & Business",
    "Pharmacy / Drugstore": "Health & Beauty",
    "Sunglasses & eyewear shop": "Fashion & Accessories",
    "Comfort food restaurant": "Food & Beverage",
    "Printing Service": "Office & Business",
    "GP practice": "Health & Beauty",
    "Building materials": "Home & Garden",
    "Vehicle, aircraft and boat": "Transportation",
    "Motor vehicle company": "Automotive",
    "Science, Technology & Engineering": "Science & Technology",
    "Medical centre": "Health & Beauty",
    "Financial Consultant": "Finance & Consulting",
    "Urban farm": "Other",
    "Gelato Shop": "Food & Beverage",
    "Gift shop": "Retail",
    "Food & beverage": "Food & Beverage",
    "Pet groomer": "Pets & Animals",
    "Corporate office": "Office & Business",
    "Musician": "Arts & Entertainment",
    "Bus route": "Transportation",
    "Computer shop": "Electronics",
    "Dessert shop": "Food & Beverage",
    "Sports & recreation": "Sports & Recreation",
    "Finance": "Finance & Consulting",
    "Business consultant": "Consulting",
    "Event planner": "Events & Entertainment",
    "Restaurant": "Food & Beverage",
    "Performing Arts School": "Education",
    "Shopping service": "Retail",
    "Government organisation": "Politics & Government",
    "Family-style restaurant": "Food & Beverage",
    "Public service": "Politics & Government",
    "Jewellery & watches company": "Fashion & Accessories",
    "Design & fashion": "Fashion & Accessories",
    "Yoga studio": "Health & Beauty",
    "Furniture shop": "Home & Garden",
    "Clothing shop": "Fashion & Accessories",
    "Clothing (Brand)": "Fashion & Accessories",
    "Childcare service": "Family & Childcare",
    "Office supplies": "Office & Business",
    "Sunglasses & Eyewear Store": "Fashion & Accessories",
    "Digital creator": "Other",
    "Food Consultant": "Food & Beverage",
    "Hotel": "Hospitality",
    "Seasonal shop": "Retail",
    "Apparel & clothing": "Fashion & Accessories",
    "Company": "Other",
    "Language school": "Education",
    "Political candidate": "Politics & Government",
    "Personal blog": "Media & Publication",
    "Cause": "Community & Non-profit",
    "Graphic Designer": "Arts & Entertainment",
    "Farm": "Other",
    "Health Spa": "Health & Beauty",
    "Robotics Company": "Science & Technology",
    "Advertising Agency": "Advertising & Marketing",
    "Food Stand": "Food & Beverage",
    "Computer Repair Service": "Electronics",
    "Convention centre": "Events & Entertainment",
    "Business Center": "Office & Business",
    "Indian restaurant": "Food & Beverage",
    "Real Estate Service": "Real Estate",
    "Publisher": "Media & Publication",
    "Preschool": "Education",
    "Beach": "Travel & Tourism",
    "Landscape company": "Home & Garden",
    "Wine, Beer & Spirits Store": "Food & Beverage",
    "Wholesale and supply shop": "Retail",
    "Comfort Food Restaurant": "Food & Beverage",
    "Farmers' market": "Food & Beverage",
    "Medical Company": "Health & Beauty",
    "Security guard service": "Security",
    "Photographer": "Arts & Entertainment",
    "Cafe": "Food & Beverage",
    "Mediterranean Restaurant": "Food & Beverage",
    "Charity Organization": "Community & Non-profit",
    "Wine/Spirits": "Food & Beverage",
    "Accessories": "Fashion & Accessories",
    "Motorcycle Manufacturer": "Automotive",
    "Non-Governmental Organization (NGO)": "Community & Non-profit",
    "App page": "Technology & Internet",
    "Legal Service": "Legal Services",
    "Clothing store": "Fashion & Accessories",
    "Sandwich shop": "Food & Beverage",
    "College & university": "Education",
    "Chemical Company": "Science & Technology",
    "Wine, beer & spirits shop": "Food & Beverage",
    "Mattress Manufacturer": "Home & Garden",
    "Personal coach": "Other",
    "Media/news company": "Media & Publication",
    "Coach": "Other",
    "Wine bar": "Food & Beverage",
    "Carpet & Flooring Store": "Home & Garden",
    "Property investment company": "Real Estate",
    "Intellectual Property Lawyer": "Legal Services",
    "Grocery Store": "Food & Beverage",
    "Photography and videography": "Arts & Entertainment",
    "Music": "Arts & Entertainment",
    "Vitamins/supplements": "Health & Beauty",
    "Nonprofit organization": "Community & Non-profit",
    "Petrol station": "Automotive",
    "Malaysian Restaurant": "Food & Beverage",
    "Medical service": "Health & Beauty",
    "Convenience Store": "Retail",
    "Swimming Pool & Hot Tub Service": "Sports & Recreation",
    "Software Company": "Technology & Internet",
    "Gift Shop": "Retail",
    "Performance & Event Venue": "Events & Entertainment",
    "Automotive Store": "Automotive",
    "Fast food restaurant": "Food & Beverage",
    "Amusement & Theme Park": "Sports & Recreation",
    "Community College": "Education",
    "Petroleum service": "Utilities",
    "Computers & Internet Website": "Technology & Internet",
    "Fish Market": "Food & Beverage",
    "Beauty Salon": "Health & Beauty",
    "Pest Control Service": "Home & Garden",
    "Breakfast & brunch restaurant": "Food & Beverage",
    "Computer company": "Technology & Internet",
    "Property Management Company": "Real Estate",
    "Oil lube & filter service": "Automotive",
    "Audio Visual Equipment Store": "Electronics",
    "Nutritionist": "Health & Beauty",
    "Wine/spirits": "Food & Beverage",
    "Butcher Shop": "Food & Beverage",
    "Florist": "Home & Garden",
    "Baby goods/kids goods": "Children's Goods",
    "Frozen Yogurt Shop": "Food & Beverage",
    "Industrial Company": "Industrial",
    "Awning Supplier": "Home & Garden",
    "Marketing Agency": "Advertising & Marketing",
    "Car hire": "Transportation",
    "Real Estate Company": "Real Estate",
    "Commercial & industrial equipment supplier": "Industrial",
    "Retail bank": "Finance & Consulting",
    "Arcade": "Entertainment",
    "Comedy club": "Entertainment",
    "Fish market": "Food & Beverage",
    "Home Security Company": "Home & Garden",
    "Diner": "Food & Beverage",
    "Organic food shop": "Food & Beverage",
    "Actor": "Arts & Entertainment",
    "Solar energy service": "Utilities",
    "Book": "Media & Publication",
    "Automotive, Aircraft & Boat": "Transportation",
    "Political Organization": "Politics & Government",
}
